consul:
  host: localhost
  port: 8500
service:
  name: nestcloud-example-service
  port: 3000
  healthCheck:
    timeout: 1s
    interval: 10s
    protocol: http
    route: /health
config:
  name: ${{ service.name }}-config
loadbalance:
  rule: RandomRule
logger:
  level: info
  transports:
    - transport: console
      colorize: true
      datePattern: YYYY-MM-DD h:mm:ss
      label: ${{ service.name }}
